version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    command: npm run dev # overwrites RUN in Dockerfile