version: '3'

services:
  app:
    build:
      context: ./app
      args:
        - NODE_ENV=development
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules # do not overwrite the containers node_modules with local
    ports:
      - "8080:8080"
      - "9229:9229" # expose the debug port
    command: npm run dev