version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
      - "3000:3000"
    command: npx concurrently 'npm run --prefix server dev' 'npm start --prefix client' # overwrites RUN in Dockerfile