# google cloud build CI to cloud run config

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: src
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/{TODO_SET_SERVICE_NAME}:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  dir: src
  args: ['push', 'gcr.io/$PROJECT_ID/{TODO_SET_SERVICE_NAME}:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: src
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '{TODO_SET_SERVICE_NAME}'
  - '--image'
  - 'gcr.io/$PROJECT_ID/{TODO_SET_SERVICE_NAME}:$COMMIT_SHA'
  - '--region'
  - 'europe-north1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'gcr.io/$PROJECT_ID/{TODO_SET_SERVICE_NAME}:$COMMIT_SHA'